Iam2Jo/Hogwartalk

app/tmp/page.tsx, components/ChatRoomInfoModal/ChatRoomInfoModal.styles.ts, components/ChatRoomInfoModal/ChatRoomInfoModal.tsx, components/ChatRoomInfoModal/index.ts, package-lock.json, package.json
=> Feat: 채팅방 정보 모달 기능 추가

app/page.tsx, components/FriendSearchToggle/FriendSearchToggle.styles.ts, components/FriendSearchToggle/FriendSearchToggle.tsx, components/Header/Header.tsx, components/MyPageToggle/MyPageToggle.tsx
- 친구 목록 불러오기 기능 추가, 접속 유무 포함
<br/>
- 친구들의 기숙사 정보는 파이어베이스 연동 아직 안된 걸로 알고 있습니다. 추후에 작업 예정
=> Feat: 친구 목록 불러오기 기능 추가, 접속 유무 포함

app/club/club.tsx, components/club/joinModal/joinModal.styles.ts
- 네 개의 기숙사 미노출 처리
- 클럽 채팅방 참가하기 모달 크기 수정
<br/>
-
=> Feat: 네 개의 기숙사 미노출 처리, Design: 모달 크기 수정

components/ChatRoomInfoModal/ChatRoomInfoModal.tsx, components/Dormitory/Dormitory.tsx, hooks/createDormitoryIfNone.ts, package-lock.json
- 기숙사 정보 recoil state에서 db data로 변경
=> Refactor: 기숙사 정보 recoil state에서 db data로 변경

components/Dormitory/Dormitory.styles.tsx, components/Dormitory/Dormitory.tsx, components/InviteToChatRoomModal/InviteToChatRoomModal.tsx
- 기숙사 채팅방에서 사용자 초대 모듈 비활성화 및 초대시 유저 정보 db에 저장
=> Feat: 기숙사 채팅방에서 사용자 초대 모듈 비활성화 및 초대시 유저 정보 db에 저장

components/ChatRoomInfoModal/ChatRoomInfoModal.tsx, components/Dormitory/Dormitory.tsx, components/InviteToChatRoomModal/InviteToChatRoomModal.tsx, hooks/useFireFetch.ts
- 소켓 무한호출 에러 수정
- 채팅 안보이는 버그 수정
- 기숙사 채팅방에서 사용자 초대 모듈 비활성화 및 초대시 유저 정보 db에 저장
<br/>
- 머지 후 dev에서 테스트 하겠습니다!
=> T2 68  feature/fix render chatting

app/club/club.tsx, components/club/createModal/CreateModal.tsx, recoil/chatList.ts
- 채팅방 updateAt 기준 최신순으로 정렬될 수 있도록 로직 추가
- 채팅방 create시 해당 채팅방으로 바로 이동될 수 있도록 로직 추가
<br/>
=> Feat: club 채팅방 updateAt 기준 최신순 정렬, 채팅방 등록시 채팅방 이동 기능 추가

components/Dormitory/Dormitory.styles.tsx, components/Dormitory/Dormitory.tsx, components/InviteToChatRoomModal/InviteToChatRoomModal.tsx
- 기숙사 채팅방들에서 초대하기 모달 disable
- 사용자 추가시 firebase update 로직 수정
=> T2 87  feature/qa debug2/fix modal

app/club/chatting/chatting.tsx, app/signup/page.tsx, components/Dormitory/Dormitory.tsx, components/MyChatting/MyChatting.tsx, components/club/chatItem/chatItem.tsx, components/club/createModal/CreateModal.tsx, components/club/joinModal/joinModal.tsx
=> Fix: 채팅 안보이는 현상 해결

app/club/chatting/page.tsx, app/club/club.styles.ts, app/club/club.tsx, app/home/page.tsx, app/layout.tsx, app/selectDormitory/gryffindor/page.tsx, app/selectDormitory/hufflepuff/page.tsx, app/selectDormitory/page.tsx, app/selectDormitory/ravenclaw/page.tsx, app/selectDormitory/selectDormitory.tsx, app/selectDormitory/slytherin/page.tsx, app/signup/page.tsx, components/Dormitory/Dormitory.styles.tsx, components/FriendSearchToggle/socket.js, components/Header/Header.styles.ts, components/Header/Header.tsx, components/Header/icons/LogoutIcon.tsx, components/MyChatting/MyChatting.styles.tsx, package-lock.json, package.json, utils/logout.ts
- Header 관련 UI 작업 
- logout 로직 추가
<br/>
- <Header />가 나타나야 하는 page들에 넣었습니다.
=> T2 89  feature/refactor UI logout

components/FriendSearchToggle/FriendSearchToggle.tsx, utils/firebase.ts
- 코드 로직 변경 사항 X
- 필요 없는 부분 정리
<br/>
- FriendSearchToggle.tsx에서 수정하고 저장하는 순간은 접속 유무 표시가 잘 되고 곧바로 다시 모든 사람이 미접속로 들어오는데 이유를 모르겠어요 @seungsimdang
=> T2 77  feature/refactor friendsearch toggle

app/selectDormitory/selectDormitory.tsx, components/Dormitory/Dormitory.tsx
- chatId null값으로 설정되는 현상 수정
- 채팅방 참여시 본인 추가 안되는 현상 수정
- 나가기 시 selectDormitory 페이지로 이동
=> T2-93-feature/qa-debug3/debug

app/club/club.tsx, app/page.tsx, app/selectDormitory/gryffindor/gryffindor.tsx, app/selectDormitory/hufflepuff/hufflepuff.tsx, app/selectDormitory/ravenclaw/ravenclaw.tsx, app/selectDormitory/selectDormitory.tsx, app/selectDormitory/slytherin/slytherin.tsx, app/signup/page.tsx, utils/service.js
- 로그인 안한상태에서 url 접근시 로그인 페이지 유도
-  service 에러핸들링
<br/>
-
=> T2-91--feature/serviceRefactor 로그인 안한상태에서 url 접근시 로그인 페이지 유도 + service 에러핸들링

components/Dormitory/Dormitory.styles.tsx, components/Dormitory/Dormitory.tsx, components/club/createModal/CreateModal.tsx
- 나가기 누르면 club 목록으로 이동
<br/>
- X
=> Feat: 나가기 누르면 club 목록으로 이동

README.md
=> Doc: README.md 작성

components/ChatRoomInfoModal/ChatRoomInfoModal.tsx, components/Dormitory/Dormitory.tsx
=> Feat: 기숙사 채팅방 못나가게 설정

components/FriendSearchToggle/FriendSearchToggle.tsx, hooks/useChatSocketHooks.ts
=> Fix: 친구목록 접속 유무 표시 안되는 에러 수정

app/page.tsx, components/Dormitory/Dormitory.styles.tsx, components/Dormitory/Dormitory.tsx, components/FriendSearchToggle/FriendSearchToggle.tsx, utils/service.js
- 헤더 메뉴바 스타일 수정 + 로그인 페이지 에러 해결
<br/>
-
=> T2 97 header fix 헤더 메뉴바 스타일 수정 + 로그인 페이지 에러 해결

components/Dormitory/Dormitory.styles.tsx, components/Dormitory/Dormitory.tsx, components/MyChatToggle/MyChatToggle.styles.ts, components/MyChatting/MyChatting.styles.tsx, components/MyPageToggle/MyPageToggle.styles.ts
- 채팅방 더보기 토글 (구분선, 화면 밖에 클릭시 닫히게)
- 클럽채팅방 목록 호버 효과
- 참여중인채팅방 호버 효과
<br/>
- X
=> T2 89  feature/refactor UI

app/club/[id]/page.tsx, app/club/chatting/chatting.tsx, app/club/club.tsx, app/selectDormitory/selectDormitory.tsx, components/ChatRoomInfoModal/ChatRoomInfoModal.tsx, components/Dormitory/Dormitory.tsx, components/FriendSearchToggle/FriendSearchToggle.tsx, components/FriendSearchToggle/socket.js, components/InviteToChatRoomModal/InviteToChatRoomModal.tsx, components/MyChatToggle/MyChatToggle.tsx, components/MyChatting/MyChatting.tsx, components/MyPageToggle/MyPageToggle.tsx, components/club/chatItem/chatItem.tsx, components/club/createModal/CreateModal.tsx, components/club/joinModal/joinModal.tsx, hooks/RESTAPI/readChatting.ts, hooks/findMyId.ts, utils/service.js
=> T2 101 feature/debugging 4

next.config.js
=> Fix: next config 수정

components/FriendSearchToggle/FriendSearchToggle.tsx
=> Feat: 접속 유저 목록에 기숙사 정보 추가

components/FriendSearchToggle/FriendSearchToggle.tsx
=> T2 104  feature/add dorm info
